### ISSUE TITLE
the matlab version

### ISSUE THREAD

**Issue by lhyxyw** [michelbl/MPPCA#3]
Dear sir
I found that you did ''Translation in python of the Matlab implementation''.Could you tell me where is the link of the matlab version?

Good Luck!

**Comment by michelbl** [comment]
You can find the matlab code in this SVN repository : https://sourceforge.net/p/pgmmppca/svn/HEAD/tree/

**Comment by lhyxyw** [comment]
Dear sir ,
              Have you ever used MPPCA for fault detection experiments？

**Comment by michelbl** [comment]
That could make sense but I have no past experience of applying MPPCA to fraud detection.
